typography_spectrum: 0.16486706882613794
color:
  brandStrength: 0.8927133492328743
  lightness: 0.32749001439457925
  saturation: 0.5187025472087472
  rhythmicContrast: 0.6387493578903377
  brandColors:
    - '#7282B6'
    - '#FEFEFE'
    - '#CDBD9C'
    - '#C6DCF5'
    - '#27361B'
github: true
layout_spectrum: 0.03871556232185426
analytics:
  twitter: Ing. Massimiliano Lusetti
author:
  name: MyArching Team
  email: max.lusetti@archingstudio.org
name: Lago.property
url: 'https://lago.property'
colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
navigation:
  - name: L'aspetto emozionale
    id: b170fdca-15e4-43ce-9072-6c5f34be2ba2
    type: content
  - name: La visione economica e tecnica
    id: 25a4d76b-c0f0-47ea-b13f-8edaa18e2e40
    type: content
  - name: Il calendario del piano
    id: 1cc733b0-f7b6-49a8-93e0-73d20948b312
    type: content
title: 'MyArching #ProgettoLAgo'
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: video
    html: >-
      <iframe
      src="https://cdn.embedly.com/widgets/media.html?src=https%3A%2F%2Fwww.youtube.com%2Fembed%2Fu5V1R7DsLdw%3Ffeature%3Doembed&url=http%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3Du5V1R7DsLdw&image=https%3A%2F%2Fi.ytimg.com%2Fvi%2Fu5V1R7DsLdw%2Fhqdefault.jpg&key=b7d04c9b404c499eba89ee7072e1c4f7&type=text%2Fhtml&schema=youtube"
      width="640" height="360" scrolling="no" frameborder="0"
      allowfullscreen></iframe>
    src: !<tag:yaml.org,2002:js/undefined> ''
    metadata:
      datePublished: null
      isBasedOnUrl: 'https://youtu.be/u5V1R7DsLdw'
      keywords:
        - '#zenui'
        - '#minimovie'
        - '#slideshowhappy'
      related: []
      author:
        - name: Max Lusetti
          url: 'https://www.youtube.com/user/archingstudio1'
          avatar: {}
      '@context': 'http://schema.org'
      title: 28 mag 2017
      '@type': VideoObject
      app_links:
        - url: 'vnd.youtube://www.youtube.com/watch?v=u5V1R7DsLdw&feature=applinks'
          type: ios
          namespace: ai
          app_store_id: '544007664'
          app_name: YouTube
        - url: 'vnd.youtube://www.youtube.com/watch?v=u5V1R7DsLdw&feature=applinks'
          type: android
          namespace: ai
          app_name: YouTube
          package: com.google.android.youtube
        - url: 'https://www.youtube.com/watch?v=u5V1R7DsLdw&feature=applinks'
          type: web
          namespace: ai
        - url: 'vnd.youtube://www.youtube.com/watch?v=u5V1R7DsLdw&feature=applinks'
          namespace: twitter
          type: ipad
          name: YouTube
          id: '544007664'
        - url: 'vnd.youtube://www.youtube.com/watch?v=u5V1R7DsLdw&feature=applinks'
          namespace: twitter
          type: iphone
          name: YouTube
          id: '544007664'
        - url: 'https://www.youtube.com/watch?v=u5V1R7DsLdw'
          namespace: twitter
          type: googleplay
          name: YouTube
          id: com.google.android.youtube
        - path: http/www.youtube.com/watch?v=u5V1R7DsLdw
          package: com.google.android.youtube
          namespace: google
          type: android
        - path: vnd.youtube/www.youtube.com/watch?v=u5V1R7DsLdw
          package: '544007664'
          namespace: google
          type: ios
      publisher:
        url: 'https://www.youtube.com/'
        name: YouTube
        favicon: 'https://s.ytimg.com/yts/img/favicon-vflz7uhzw.ico'
        domain: youtu.be
      description: My MiniMovie - Happy for 2017 (ZenUI)
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: promozione sociale e architettonica dell'antico borgo di L'Ago - Val di Vara
purpose:
  - type: external
    url: 'https://goo.gl/forms/HzFXUv1R2bX0XqpZ2'
    label: Preadesione Proprietari
  - type: external
    url: 'http://massimiliano.lusetti.mtalk.net/'
    label: chiamata on line
